# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0089ba7ec348df581f4b077404110f76dc92ce547072c6813a80ea36303603b6da3cc885173eed33f8e0fe3e4c976965fa11489e9cc468d6f56858d88769fdc2

test:
  secret_key_base: da6eb058d44ca75fd23bf0fd81a349fdc8831ed8d2583a64837d2f352aad0cb07aa3240a1db559f9a4ce3acfce002354e6dafb3e5d1274c0712832f5534becd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
